### ISSUE TITLE
Simplificaciones booleanas

### ISSUE THREAD

**Issue by NBbrook** [SistemasTecTlaxiaco/actividad-10-expresiones-boolenas-club-noobbaby#1]
[Simplificación Boleanas.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-expresiones-boolenas-club-noobbaby/files/13621455/Simplificacion.Boleanas.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
